---
- hosts: all
  become: true
  vars_files:
    - ./variables/default.yml
  tasks:
    - name: Install MySQL
      apt:
        state: present
        update_cache: yes
        name:
          - mysql-server
          - python-mysqldb
      #Generate new root password
    - name: Create WordPress MySQL database
      mysql_db: name="{{ wp_db_name }}" state=present
    - name: Create WordPress MySQL user
      mysql_user: name="{{ wp_db_user }}" host=localhost password="{{ wp_db_password }}" priv=wordpress.*:ALL

    - name: Copy wordpress database backup
      copy:
        src: ./files/mysql/wordpressBackup.sql
        dest: /tmp/wordpressBackup.sql
        owner: root
        group: root
        mode: 0777

    - name: Import WordPress DB
      mysql_db: target=/tmp/wordpressBackup.sql state=import name="{{ wp_db_name }}"
