---
- hosts: all
  become: true
  vars_files:
    - ./variables/default.yml
  tasks:
    - name: Copy wordpress.zip into tmp
      copy: 
        src: ./files/wordpress.zip 
        dest: /tmp/wordpress.zip

    - name: Unzip WordPress
      unarchive: 
        src: /tmp/wordpress.zip 
        dest: /tmp/
        copy: no 
        creates: /tmp/wordpress/wp‐settings.php

    - name: Copy WordPress files
      copy: 
        remote_src: True
        src: /tmp/wordpress/
        dest: "{{ wp_root }}"
      
    - name: Copy WordPress files
      copy: 
        src: ./templates/wordpress/wp-config.php
        dest: "{{ wp_root }}/wp-config.php"